title: Juan Felipe Mendez-Valderrama
email: som.felipe66 -at- gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 Welcome! I'm a theoretical condensed matter physicist. Currently I am a PCCM postdoctoral fellow at Princeton University working in the group of Andrei Bernevig. 
github_username:  MendezV
google_analytics:
theme: jekyll-theme-cayman
